name: AdvancedCommunication
version: ${project.version}
main: me.ajan12.advancedcommunication.AdvancedCommunication
api-version: 1.13
authors: [ajan_12]
description: Advanced communication methods for your Spigot server!

commands:
  message:
    description: Start a messaging session or send a single message to another player!
    aliases: [msg, privatemessage, private-message, pmsg, dm, dmsg, directmessage, direct-message]