name: AdvancedCommunication
version: ${project.version}
main: me.ajan12.advancedcommunication.AdvancedCommunication
authors: [ajan_12]
depend: [ProtocolLib,Vault]
description: Advanced communication methods for your Spigot server!

commands:

  advancedcommunication:
    description: Main command of the plugin.
    aliases: [ac, advc, acomm, advcomm]

  group:
    description: Main command to access group features.
    aliases: [g, gr, groups]
    usage: /group help

  message:
    description: Start a messaging session or send a single message to another player!
    aliases: [msg, privatemessage, private-message, pmsg, dm, dmsg, directmessage, direct-message]
    usage: /message help

  reply:
    description: Send a message to the last person you messaged.
    aliases: [r]
    usage: /reply help

  ignore:
    description: Toggles the ignoring state of a player for another player.
    usage: /ignore help

  softmute:
    description: Softmutes or un-softmutes a player.
    aliases: [sm, softm, smute]
    usage: /softmute help

  hardmute:
    description: Hardmutes or un-hardmutes a player.
    aliases: [hm, hardm, hmute, mute]
    usage: /hardmute help

permissions:

  #### Help page
  advancedcommunication.command.help:
    description: The permission node that defines if a player is able to view the help page.
    default: op

  #### Group creating command
  advancedcommunication.command.group.create:
    description: The permission node that defines if a player is able to create a group.
    default: true

  #### Softmute command
  advancedcommunication.command.softmute:
    description: The permission node that defines if a player can use softmute command.
    default: op

  #### Hardmute command
  advancedcommunication.command.hardmute:
    description: The permission node that defines if a player can use hardmute command.
    default: op

  #### Saving/Purging commands
  advancedcommunication.command.save.groups:
    description: The permission node that defines if a player is able to save the all of groups.
    default: op
  advancedcommunication.command.purge.groups:
    description: The permission node that defines if a player is able to purge the all of groups.
    default: op
  advancedcommunication.command.save.users:
    description: The permission node that defines if a player is able to save the all of users.
    default: op
  advancedcommunication.command.purge.users:
    description: The permission node that defines if a player is able to purge the all of users.
    default: op

  advancedcommunication.command.save.group:
    description: The permission node that defines if a player is able to save a group.
    default: op
  advancedcommunication.command.purge.group:
    description: The permission node that defines if a player is able to purge a group.
    default: op
  advancedcommunication.command.save.user:
    description: The permission node that defines if a player is able to save an user.
    default: op
  advancedcommunication.command.purge.user:
    description: The permission node that defines if a player is able to purge an user.
    default: op

  #### Spy toggling command
  advancedcommunication.command.spy.other:
    description: The permission node that defines if a player is able to toggle spying of someone else.
    children:
      advancedcommunication.command.help: true
    default: op

  advancedcommunication.command.spy.self:
    description: The permission node that defines if a player is able to toggle spying of themselves.
    children:
      advancedcommunication.command.help: true
    default: op

  advancedcommunication.command.spy.*:
    description: The permission node that defines if a player is able to toggle spying of themselves and of someone else.
    children:
      advancedcommunication.command.spy.other: true
      advancedcommunication.command.spy.self: true
      advancedcommunication.command.help: true
    default: op

  #### Spy
  advancedcommunication.spy:
    description: The permission node that defines if a player is spying.
    default: op

  #### User purging bypass
  advancedcommunication.user.purge.bypass:
    description: The permission node that makes the player unable to be purged.
    default: op